services:
  - type: web
    name: danang-investbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rag_chatbot.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rag_chatbot.settings
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: PORT
        value: '8000'